import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";



const montserrat = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}  antialiased bg-[#050807]`}>
        <div className='fixed top-0 left-0 right-0 z-50'>
          {/* <Header /> */}
        </div>
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
