export const musicTypes = [
    "A Capella",
    "Bossa Nova",
    "Chamber",
    "Choral",
    "Concert Music",
    "Electroacoustic (Acousmatic)",
    "Electroacoustic (Mixed)",
    "Instrumental",
    "Jazz",
    "Microtonal",
    "(Quasi-)Microtonal",
    "Music for Dance",
    "Opera (Narrated Tale)",
    "Opera (Chamber)",
    "Opera (Monodrama)",
    "Orchestral",
    "Song",
    "VST",
    "Vocal",
];

export const instrumentationAndResources = {
    Instrumentation: [
        "Big Band",
        "Bossa Nova Ensemble",
        "Choir (Operatic)",
        "Choir (SATB)",
        "Choir (SATBB)",
        "Duo",
        "Guitar Quartet",
        "Jazz Ensemble",
        "Mixed Ensemble",
        "Solo",
        "String Quartet",
        "Trio",
        "Vocal Octet (with Beatbox)",
        "Vocal Quartet (with Beatbox)",
        "Vocal Sextet (with Beatbox)",
        "Wind Orchestra (Small)",
    ],
    Instruments: [
        "Accordion",
        "Bassoon",
        "Cello",
        "Clarinet (Bb)",
        "Clarinet (Bass)",
        "Double Bass",
        "Drums",
        "Guitar (Bass, Electric)",
        "Guitar (Classical)",
        "Guitar (Electric)",
        "Flute (C)",
        "Flute (Alto)",
        "Flute (Piccolo)",
        "Harp",
        "Horn (F)",
        "Keyboard (Electric)",
        "Keyboard (MIDI)",
        "Laptop",
        "Lumatone",
        "Oboe (Soprano)",
        "Oboe (Cor Anglais)",
        "Organ (Pipe)",
        "Piano",
        "Percussion",
        "Saxophone (Alto)",
        "Saxophone (Tenor)",
        "Trombone (Tenor)",
        "Trombone (Bass)",
        "Trumpet (Bb)",
        "Tuba",
        "Violin",
        "Viola",
        "Voice (Alto)",
        "Voice (Baritone)",
        "Voice (Bass)",
        "Voice (Beatbox)",
        "Voice (Countertenor)",
        "Voice (Mezzo)",
        "Voice (Narrator)",
        "Voice (Soprano)",
        "Voice (Tenor)",
    ],
    "Electronic Resources": ["1 or 2 Speakers", "2 Speakers", "bitKlavier", "Max/MSP", "Pianoteq"],
};

export const tuningSystems = {
    "Equal Divisions of the Octave (EDO)": [
        "2EDO",
        "3EDO",
        "4EDO",
        "5EDO",
        "6EDO",
        "7EDO",
        "8EDO",
        "9EDO",
        "10EDO",
        "11EDO",
        "12EDO",
        "13EDO",
        "17EDO",
        "19EDO",
        "23EDO",
        "26EDO",
        "29EDO",
        "31EDO",
        "48EDO",
        "50EDO",
    ],
    "Equal Divisions of Other Intervals": [
        "1ED3/2",
        "2ED3/2",
        "3ED3/2",
        "4ED3/2",
        "5ED3/2",
        "6ED3/2",
        "7ED3/2",
        "6ED7/5",
        "4ED11/7",
        "2ED5\\12EDO",
        "2ED7\\12EDO",
        "1ED11\\12EDO",
        "2ED11\\12EDO",
        "3ED11\\12EDO",
        "4ED11\\12EDO",
        "5ED11\\12EDO",
        "6ED11\\12EDO",
        "7ED11\\12EDO",
        "8ED11\\12EDO",
        "9ED11\\12EDO",
    ],
    "Other Systems": [
        "12 Notes per Octave",
        "24 Notes per Octave",
        "48 Notes per Octave",
        "72 Notes per Octave",
        "1/4 Comma Meantone Temperament",
        "Approximated Equal Tunings",
        "Just Intonation",
        "Distorted Harmonic Series",
    ],
};
