export type MusicEntry = {
    category: string
    title: string
    year: string
    instrumentation: string
    duration: string
    additionalInfo?: string
    description: string
    videoLinks?: string[]
    scoreLink?: string
}

export type MusicType = string

export type InstrumentationCategory = "Instrumentation" | "Instruments" | "Electronic Resources"

export type InstrumentationAndResources = {
    [key in InstrumentationCategory]: string[]
}

export type TuningSystemCategory =
    | "Equal Divisions of the Octave (EDO)"
    | "Equal Divisions of Other Intervals"
    | "Other Systems"

export type TuningSystems = {
    [key in TuningSystemCategory]: string[]
}

export const allEntries: MusicEntry[] = [
    {
        category: "Compositions",
        title: "... spiraling.",
        year: "2024/2025",
        instrumentation: "for the Lumatone",
        duration: "1'30''",
        additionalInfo: "Poem by Eugenio de Andrade",
        description: "Written in commemoration of Alexandra Mouroutsou's 10th birthday.",
    },
    {
        category: "Compositions",
        title: "Contigo",
        year: "2023",
        instrumentation: "for voice and piano",
        duration: "4'30''",
        description: "A heartfelt composition exploring the depths of companionship.",
        videoLinks: ["https://www.youtube.com/watch?v=sje-9JSeY4o"],
        scoreLink:
            "https://8bfb0c4a-9145-4292-aa38-862bb8c72be2.filesusr.com/ugd/644baf_4535701f090d4a388aaf5515485d59d0.pdf",
    },
    {
        category: "Compositions",
        title: "Convergence",
        year: "2023",
        instrumentation: "for ensemble",
        duration: "6'00''",
        description: "An exploration of musical elements coming together.",
    },
    {
        category: "Compositions",
        title: "Seeking Gnosis",
        year: "2022",
        instrumentation: "for chamber ensemble",
        duration: "7'30''",
        description: "A musical journey towards spiritual knowledge.",
    },
    {
        category: "Compositions",
        title: "The Fable of the Pilgrim",
        year: "2022",
        instrumentation: "for orchestra",
        duration: "12'00''",
        description: "A musical narrative of a pilgrim's journey.",
    },
    {
        category: "Compositions",
        title: "Odd [s]Paces",
        year: "2022",
        instrumentation: "for electronics",
        duration: "8'45''",
        description: "An electronic piece exploring unusual sonic spaces.",
    },
    {
        category: "Compositions",
        title: "Dreams from an Old Memory",
        year: "2022",
        instrumentation: "for piano",
        duration: "5'30''",
        description: "A nostalgic piece evoking distant memories.",
    },
    {
        category: "Compositions",
        title: "A Escolha de Paulo",
        year: "2022",
        instrumentation: "for chamber ensemble",
        duration: "8'00''",
        description: "An exploration of choice and consequence through music.",
        videoLinks: ["https://www.youtube.com/watch?v=v5kzRweEB0M"],
        scoreLink:
            "https://8bfb0c4a-9145-4292-aa38-862bb8c72be2.filesusr.com/ugd/644baf_5c1406c161364b86bea3b594e0b5de9e.pdf",
    },
    {
        category: "Compositions",
        title: "Adão",
        year: "2021",
        instrumentation: "for solo piano",
        duration: "6'15''",
        description: "A contemplative piece inspired by the biblical figure of Adam.",
        videoLinks: ["https://www.youtube.com/watch?v=WwP_RVeQ_8Y"],
    },
    {
        category: "Compositions",
        title: "PRISM",
        year: "2021",
        instrumentation: "for electronics",
        duration: "5'45''",
        description: "An electronic composition exploring the concept of refraction.",
        videoLinks: ["https://www.youtube.com/watch?v=fQnDYNsEvaY"],
    },
    {
        category: "Compositions",
        title: "Have you ever met a human before?",
        year: "2021",
        instrumentation: "for ensemble",
        duration: "7'00''",
        description: "A piece questioning the nature of human interaction.",
    },
    {
        category: "Compositions",
        title: "Transeuntes",
        year: "2020",
        instrumentation: "for mixed ensemble",
        duration: "12'00''",
        description: "A suite inspired by the transient nature of urban life.",
        videoLinks: [
            "https://www.youtube.com/watch?v=T66FvUUuJpg",
            "https://www.youtube.com/watch?v=zIuBLoC2NbQ",
            "https://www.youtube.com/watch?v=7g2IBdn9x7Q",
        ],
        scoreLink: "https://pedroffinisterra.bandcamp.com/album/transeuntes",
    },
    {
        category: "Compositions",
        title: "Babel",
        year: "2019",
        instrumentation: "for choir",
        duration: "7'30''",
        description: "A choral work exploring the myth of the Tower of Babel.",
        videoLinks: ["https://www.youtube.com/watch?v=t88u4xz8Lac"],
        scoreLink:
            "https://8bfb0c4a-9145-4292-aa38-862bb8c72be2.filesusr.com/ugd/644baf_68411c9e6d404100a5019e60f660e19f.pdf",
    },
    {
        category: "Compositions",
        title: "El Laberinto de Nijinsky",
        year: "2019",
        instrumentation: "for orchestra",
        duration: "15'00''",
        description: "A musical portrayal of Vaslav Nijinsky's complex life and artistry.",
        videoLinks: ["https://www.youtube.com/watch?v=nZXaej6lnkA"],
    },
    {
        category: "Compositions",
        title: "Ne Ago",
        year: "2019",
        instrumentation: "for ensemble",
        duration: "6'30''",
        description: "A piece exploring the concept of negation in music.",
        videoLinks: ["https://www.youtube.com/watch?v=6xXhNt_vpcY"],
    },
    {
        category: "Compositions",
        title: "La vojaĝo",
        year: "2018",
        instrumentation: "for chamber ensemble",
        duration: "8'45''",
        description: "A musical journey inspired by Esperanto.",
        videoLinks: ["https://www.youtube.com/watch?v=OXOg7pixHIM"],
        scoreLink:
            "https://8bfb0c4a-9145-4292-aa38-862bb8c72be2.filesusr.com/ugd/644baf_d302725fd7fd429e90131895391d8804.pdf",
    },
    {
        category: "Compositions",
        title: "MA.RIM.BA",
        year: "2018",
        instrumentation: "for marimba",
        duration: "5'00''",
        description: "A solo piece exploring the sonic possibilities of the marimba.",
        videoLinks: ["https://oneglasseye.bandcamp.com/track/ma-rim-ba"],
        scoreLink:
            "https://8bfb0c4a-9145-4292-aa38-862bb8c72be2.filesusr.com/ugd/644baf_d5c0ae9b5607448589ee70922e57a6ff.pdf",
    },
    {
        category: "Compositions",
        title: "The Boy Who Wanted to be a Robot",
        year: "2018",
        instrumentation: "for electronics",
        duration: "7'15''",
        description: "An electronic piece exploring the intersection of humanity and technology.",
        videoLinks: ["http://youtube.com/watch?v=IDM0THAddQs"],
        scoreLink:
            "https://8bfb0c4a-9145-4292-aa38-862bb8c72be2.filesusr.com/ugd/644baf_3a857159c0944a99a50721b823221de7.pdf",
    },
    {
        category: "Compositions",
        title: "Nymphus: Mithraic Initiation Rite Number Two",
        year: "2017",
        instrumentation: "for ensemble",
        duration: "9'30''",
        description: "A piece inspired by ancient Mithraic rituals.",
        videoLinks: ["https://www.youtube.com/watch?v=-A3b3joAFPA"],
        scoreLink:
            "https://8bfb0c4a-9145-4292-aa38-862bb8c72be2.filesusr.com/ugd/644baf_5fd76c3f541340a7a8b7738d21d6110b.pdf",
    },
    {
        category: "Compositions",
        title: "Multidão - I. Primeiro",
        year: "2017",
        instrumentation: "for orchestra",
        duration: "8'00''",
        description: "The first movement of a larger work exploring the concept of crowds.",
        videoLinks: ["https://www.youtube.com/watch?v=fl5wrPwH8ns"],
        scoreLink:
            "https://portfolios.esml.ipl.pt/oprojecto/90-criacao-circulacao-registo-audio-e-edicao-de-obras-de-musica-portuguesa-contemporanea-numa-perspetiva-reflexiva/133-multidao-i-primeiro",
    },
    {
        category: "Compositions",
        title: "@ctb.exp#1",
        year: "2017",
        instrumentation: "for double bass",
        duration: "6'45''",
        description: "An experimental piece for solo double bass.",
        videoLinks: ["https://www.youtube.com/watch?v=trajxDl1b9c"],
        scoreLink: "https://www.scherzoeditions.com/webshop/shop/ctb-exp1-para-contrabaixo-pedro-f-finisterra/",
    },
    {
        category: "Compositions",
        title: "Flor",
        year: "2016",
        instrumentation: "for ensemble",
        duration: "7'30''",
        description: "A piece inspired by the delicate nature of flowers.",
        videoLinks: ["https://www.youtube.com/watch?v=H9vDP-Ml4cM"],
        scoreLink: "https://portfolios.esml.ipl.pt/oprojecto/89-performance-colaborativa-fmh-esml/116-flor",
    },
    {
        category: "Compositions",
        title: "Lilith",
        year: "2016",
        instrumentation: "for voice and electronics",
        duration: "8'15''",
        description: "A piece exploring the mythological figure of Lilith.",
        videoLinks: ["https://www.youtube.com/watch?v=R0ZDQ-6TrhQ"],
    },
    {
        category: "Compositions",
        title: "¡¿Lamento?!",
        year: "2016",
        instrumentation: "for ensemble",
        duration: "6'00''",
        description: "A contemporary take on the traditional lament form.",
        videoLinks: ["https://www.youtube.com/watch?v=pWzALCt9cws"],
        scoreLink: "https://portfolios.esml.ipl.pt/oprojecto/98-old-is-new-concerto-1/84-lamento",
    },
    {
        category: "Compositions",
        title: "Expressões",
        year: "2015",
        instrumentation: "for piano",
        duration: "5'30''",
        description: "A solo piano piece exploring various musical expressions.",
        videoLinks: ["https://www.youtube.com/watch?v=i-wkHVZy-7g"],
        scoreLink:
            "https://8bfb0c4a-9145-4292-aa38-862bb8c72be2.filesusr.com/ugd/644baf_ed62ca3a0a6e4d06995ebf07a93cb1aa.pdf",
    },
    {
        category: "Compositions",
        title: "Introspecções",
        year: "2015",
        instrumentation: "for piano",
        duration: "4'45''",
        description: "A contemplative piece for solo piano.",
        videoLinks: ["http://youtube.com/watch?v=pPvtiPMlaw4"],
        scoreLink:
            "https://8bfb0c4a-9145-4292-aa38-862bb8c72be2.filesusr.com/ugd/644baf_0d2194cf6b614166bcbc3d5536a8ba36.pdf",
    },
    {
        category: "Compositions",
        title: "Prjkt.Hrp",
        year: "2015",
        instrumentation: "for harp",
        duration: "6'00''",
        description: "An experimental piece for solo harp.",
        videoLinks: ["https://www.youtube.com/watch?v=6J6KFcayW74"],
        scoreLink: "https://portfolios.esml.ipl.pt/oprojecto/95-semana-da-composicao-2015/156-prjkt-hrp",
    },
    {
        category: "Compositions",
        title: "Eu não sei…",
        year: "2015",
        instrumentation: "for voice and piano",
        duration: "3'30''",
        description: "A song exploring themes of uncertainty.",
        videoLinks: ["https://www.youtube.com/watch?v=N-Yz9AJJlmc"],
    },
    {
        category: "Compositions",
        title: "Plácidos Domingos",
        year: "2014",
        instrumentation: "for ensemble",
        duration: "5'45''",
        description: "A piece evoking peaceful Sunday afternoons.",
    },
    {
        category: "Compositions",
        title: "8-bits of Music",
        year: "2014",
        instrumentation: "for electronics",
        duration: "Various",
        description: "A collection of pieces inspired by 8-bit video game music.",
        videoLinks: ["https://www.youtube.com/playlist?list=PL6VcdiGfTfX6k8hNDNVxpS0hOIy3kLXpY"],
    },
    {
        category: "Compositions",
        title: "7",
        year: "2014",
        instrumentation: "for piano",
        duration: "4'00''",
        description: "A piece exploring the musical and symbolic properties of the number 7.",
        videoLinks: ["https://www.youtube.com/watch?v=-_lkcsjPGds"],
        scoreLink:
            "https://8bfb0c4a-9145-4292-aa38-862bb8c72be2.filesusr.com/ugd/644baf_0757df4751e74c8a8ba01b179fc951aa.pdf",
    },
    {
        category: "Compositions",
        title: "Flip Point & Obsession",
        year: "2014",
        instrumentation: "for ensemble",
        duration: "7'30''",
        description: "A two-part piece exploring contrasting musical ideas.",
        videoLinks: ["https://www.youtube.com/watch?v=_8ObX6182o0"],
        scoreLink: "https://portfolios.esml.ipl.pt/oprojecto/96-semana-da-composicao-2016/115-flip-point-obsession",
    },
    {
        category: "Compositions",
        title: "Óvaadasac",
        year: "2013",
        instrumentation: "for ensemble",
        duration: "6'15''",
        description: "An experimental piece with unconventional instrumentation.",
        videoLinks: ["https://www.youtube.com/watch?v=jCNf8mFrmWY"],
    },
    {
        category: "Compositions",
        title: "Harp' N Roll",
        year: "2013",
        instrumentation: "for harp",
        duration: "4'30''",
        description: "A piece blending harp techniques with rock-inspired rhythms.",
    },
    {
        category: "Compositions",
        title: "Estudo para Guitarra nº2",
        year: "2013",
        instrumentation: "for guitar",
        duration: "3'45''",
        description: "The second in a series of guitar studies.",
    },
    {
        category: "Compositions",
        title: "Dryhg oui - II",
        year: "2013",
        instrumentation: "for ensemble",
        duration: "5'00''",
        description: "The second part of the 'Dryhg oui' series.",
    },
    {
        category: "Compositions",
        title: "4 Pequenas Peças para Piano",
        year: "2012",
        instrumentation: "for piano",
        duration: "8'00''",
        description: "A set of four short pieces for solo piano.",
        videoLinks: ["https://www.youtube.com/watch?v=OO84Wd7tfuo"],
    },
    {
        category: "Compositions",
        title: "Dryhg oui - I",
        year: "2012",
        instrumentation: "for ensemble",
        duration: "4'30''",
        description: "The first part of the 'Dryhg oui' series.",
    },
    {
        category: "Compositions",
        title: "Tributo a Masashi Hamauzu",
        year: "2012",
        instrumentation: "for piano",
        duration: "3'15''",
        description: "A tribute piece to the Japanese composer Masashi Hamauzu.",
        videoLinks: ["https://www.youtube.com/watch?v=15OFS9mvX6Y"],
    },
    {
        category: "Compositions",
        title: "Aurora",
        year: "2011",
        instrumentation: "for piano",
        duration: "2'45''",
        description: "A piece evoking the beauty of the aurora phenomenon.",
        videoLinks: ["https://www.youtube.com/watch?v=_E6kXfSjeM4"],
    },
    {
        category: "Compositions",
        title: "2 Prelúdios para Guitarra",
        year: "2011",
        instrumentation: "for guitar",
        duration: "5'30''",
        description: "Two preludes for solo guitar.",
        videoLinks: ["https://www.youtube.com/playlist?list=PL6VcdiGfTfX7tCZ1FNuZNaoLfL7rTp1nx"],
    },
    {
        category: "Compositions",
        title: "1521 Gotas de Chuva",
        year: "2011",
        instrumentation: "for piano",
        duration: "3'00''",
        description: "A piece inspired by the sound of raindrops.",
        videoLinks: ["https://www.youtube.com/watch?v=RlvYXs4mpNI"],
    },
    {
        category: "Compositions",
        title: "Estudo para Guitarra nº1",
        year: "2010",
        instrumentation: "for guitar",
        duration: "2'30''",
        description: "The first in a series of guitar studies.",
        videoLinks: ["https://www.youtube.com/watch?v=viGqiocGRsg"],
    },
    {
        category: "Compositions",
        title: "Paz de Espírito",
        year: "2010",
        instrumentation: "for piano",
        duration: "2'15''",
        description: "A contemplative piece for solo piano.",
        videoLinks: ["https://www.youtube.com/watch?v=X4mExOf3YxQ"],
    },
    {
        category: "Compositions",
        title: "Submerged",
        year: "2010",
        instrumentation: "for piano",
        duration: "2'30''",
        description: "A piece evoking underwater sensations.",
        videoLinks: ["https://www.youtube.com/watch?v=p0cUcI140HE"],
    },
    {
        category: "Compositions",
        title: "... for Glenn",
        year: "2009",
        instrumentation: "for piano",
        duration: "1'45''",
        description: "A tribute piece, possibly inspired by Glenn Gould.",
        videoLinks: ["https://www.youtube.com/watch?v=vZbrgxQVM_k"],
    },
    {
        category: "Compositions",
        title: "... in the name of peace #2",
        year: "2009",
        instrumentation: "for piano",
        duration: "2'00''",
        description: "The second part of the '... in the name of peace' series.",
        videoLinks: ["https://www.youtube.com/watch?v=Wf0WqkhvEck"],
    },
    {
        category: "Compositions",
        title: "... in the name of peace #1",
        year: "2009",
        instrumentation: "for piano",
        duration: "1'30''",
        description: "The first part of the '... in the name of peace' series.",
        videoLinks: ["https://www.youtube.com/watch?v=wMMFFtJ25ww"],
    },
    {
        category: "Improvisations",
        title: "Chiptune Improvisation in 6ED7:5",
        year: "2023",
        instrumentation: "for electronics",
        duration: "3'45''",
        description: "An improvised piece using chiptune sounds in a 6ED7:5 tuning system.",
        videoLinks: ["https://pedroffinisterra.bandcamp.com/track/chiptune-improvisation-in-6ed7-5"],
    },
    {
        category: "Improvisations",
        title: "Laptop Improvisation in 7EDO",
        year: "2023",
        instrumentation: "for laptop",
        duration: "4'30''",
        description: "An improvised piece using a laptop in a 7EDO tuning system.",
        videoLinks: ["https://pedroffinisterra.bandcamp.com/track/laptop-improvisation-in-7ed2-1"],
    },
    {
        category: "Improvisations",
        title: "Tri Improvizajoj por MIDI​-​Klavaro",
        year: "2022",
        instrumentation: "for MIDI keyboard",
        duration: "15'00''",
        description: "Three improvisations for MIDI keyboard.",
        videoLinks: ["https://pedroffinisterra.bandcamp.com/album/tri-improvizajoj-por-midi-klavaro"],
    },
    {
        category: "Improvisations",
        title: "Improvisation in 17EDO",
        year: "2021",
        instrumentation: "for keyboard",
        duration: "6'30''",
        description: "An improvised piece in a 17EDO tuning system.",
        videoLinks: ["https://www.youtube.com/watch?v=6bvusHly1fI"],
    },
    {
        category: "Improvisations",
        title: "We are our dreams of ourselves",
        year: "2020",
        instrumentation: "for electronics",
        duration: "7'15''",
        description: "An improvised electronic piece exploring self-perception.",
        videoLinks: ["https://www.youtube.com/watch?v=mgzxm5BHWHs"],
    },
    {
        category: "Jazz",
        title: "Epidemia do Funk",
        year: "2017",
        instrumentation: "for jazz ensemble",
        duration: "5'45''",
        description: "A jazz piece incorporating funk elements.",
        videoLinks: ["https://www.youtube.com/watch?v=9m7Ot5SSGzI"],
    },
    {
        category: "Jazz",
        title: "Tributo a Masashi Hamauzu '16",
        year: "2016",
        instrumentation: "for jazz ensemble",
        duration: "6'30''",
        description: "A jazz tribute to the works of Masashi Hamauzu.",
        videoLinks: ["https://www.youtube.com/watch?v=93llCd-SxkA"],
    },
    {
        category: "Jazz",
        title: "Pré-primária",
        year: "2015",
        instrumentation: "for jazz ensemble",
        duration: "4'45''",
        description: "A playful jazz piece inspired by early childhood.",
        videoLinks: ["https://www.youtube.com/watch?v=DwblSFpC1dw"],
    },
    {
        category: "Jazz",
        title: "Hora de Ponta",
        year: "2014",
        instrumentation: "for jazz ensemble",
        duration: "5'15''",
        description: "A jazz piece capturing the energy of rush hour.",
        videoLinks: ["https://www.youtube.com/watch?v=d716YnF-S9I"],
        scoreLink: "https://open.spotify.com/track/5ozh6QZn2pHi0moMAEgHw8?si=6a8571a6c6994df9",
    },
    {
        category: "Jazz",
        title: "Drowning",
        year: "2013",
        instrumentation: "for jazz ensemble",
        duration: "7'00''",
        description: "A moody jazz piece evoking the sensation of drowning.",
        videoLinks: ["https://www.youtube.com/watch?v=Puj4ISWTrNI"],
    },
    {
        category: "Arrangements",
        title: "thank u, next - Ariana Grande",
        year: "2019",
        instrumentation: "for vocal ensemble",
        duration: "3'30''",
        description: "An a cappella arrangement of Ariana Grande's hit song.",
        videoLinks: [
            "https://www.youtube.com/watch?v=JzA_bvDTcD4",
            "https://www.youtube.com/live/8l9VrKSpVZE?si=lv3sfKaQ3DtE7xF4&t=837",
        ],
    },
    {
        category: "Arrangements",
        title: "Juntos Somos Mais Fortes - Amor Electro",
        year: "2018",
        instrumentation: "for vocal ensemble",
        duration: "4'00''",
        description: "An a cappella arrangement of Amor Electro's song.",
        videoLinks: [
            "https://www.youtube.com/watch?v=yG_8opUUYaI",
            "https://www.youtube.com/live/8l9VrKSpVZE?si=jNXqVWQBc_FgKkrI&t=1037",
        ],
    },
    {
        category: "Arrangements",
        title: "Lusitana Paixão - Dulce Pontes",
        year: "2017",
        instrumentation: "for vocal ensemble",
        duration: "3'45''",
        description: "An a cappella arrangement of Dulce Pontes' famous fado song.",
    },
    {
        category: "Arrangements",
        title: "Desfolhada de Inverno - Simone de Oliveira",
        year: "2016",
        instrumentation: "for vocal ensemble",
        duration: "3'15''",
        description: "An a cappella arrangement of Simone de Oliveira's classic song.",
        videoLinks: ["https://www.youtube.com/watch?v=95ihtSyw4hU"],
    },
]
export const musicTypes: MusicType[] = [
    "A Capella",
    "Bossa Nova",
    "Chamber",
    "Choral",
    "Concert Music",
    "Electroacoustic (Acousmatic)",
    "Electroacoustic (Mixed)",
    "Instrumental",
    "Jazz",
    "Microtonal",
    "(Quasi-)Microtonal",
    "Music for Dance",
    "Opera (Narrated Tale)",
    "Opera (Chamber)",
    "Opera (Monodrama)",
    "Orchestral",
    "Song",
    "VST",
    "Vocal",
]

export const instrumentationAndResources: InstrumentationAndResources = {
    Instrumentation: [
        "Big Band",
        "Bossa Nova Ensemble",
        "Choir (Operatic)",
        "Choir (SATB)",
        "Choir (SATBB)",
        "Duo",
        "Guitar Quartet",
        "Jazz Ensemble",
        "Mixed Ensemble",
        "Solo",
        "String Quartet",
        "Trio",
        "Vocal Octet (with Beatbox)",
        "Vocal Quartet (with Beatbox)",
        "Vocal Sextet (with Beatbox)",
        "Wind Orchestra (Small)",
    ],
    Instruments: [
        "Accordion",
        "Bassoon",
        "Cello",
        "Clarinet (Bb)",
        "Clarinet (Bass)",
        "Double Bass",
        "Drums",
        "Guitar (Bass, Electric)",
        "Guitar (Classical)",
        "Guitar (Electric)",
        "Flute (C)",
        "Flute (Alto)",
        "Flute (Piccolo)",
        "Harp",
        "Horn (F)",
        "Keyboard (Electric)",
        "Keyboard (MIDI)",
        "Laptop",
        "Lumatone",
        "Oboe (Soprano)",
        "Oboe (Cor Anglais)",
        "Organ (Pipe)",
        "Piano",
        "Percussion",
        "Saxophone (Alto)",
        "Saxophone (Tenor)",
        "Trombone (Tenor)",
        "Trombone (Bass)",
        "Trumpet (Bb)",
        "Tuba",
        "Violin",
        "Viola",
        "Voice (Alto)",
        "Voice (Baritone)",
        "Voice (Bass)",
        "Voice (Beatbox)",
        "Voice (Countertenor)",
        "Voice (Mezzo)",
        "Voice (Narrator)",
        "Voice (Soprano)",
        "Voice (Tenor)",
    ],
    "Electronic Resources": ["1 or 2 Speakers", "2 Speakers", "bitKlavier", "Max/MSP", "Pianoteq"],
}

export const tuningSystems: TuningSystems = {
    "Equal Divisions of the Octave (EDO)": [
        "2EDO",
        "3EDO",
        "4EDO",
        "5EDO",
        "6EDO",
        "7EDO",
        "8EDO",
        "9EDO",
        "10EDO",
        "11EDO",
        "12EDO",
        "13EDO",
        "17EDO",
        "19EDO",
        "23EDO",
        "26EDO",
        "29EDO",
        "31EDO",
        "48EDO",
        "50EDO",
    ],
    "Equal Divisions of Other Intervals": [
        "1ED3/2",
        "2ED3/2",
        "3ED3/2",
        "4ED3/2",
        "5ED3/2",
        "6ED3/2",
        "7ED3/2",
        "6ED7/5",
        "4ED11/7",
        "2ED5\\12EDO",
        "2ED7\\12EDO",
        "1ED11\\12EDO",
        "2ED11\\12EDO",
        "3ED11\\12EDO",
        "4ED11\\12EDO",
        "5ED11\\12EDO",
        "6ED11\\12EDO",
        "7ED11\\12EDO",
        "8ED11\\12EDO",
        "9ED11\\12EDO",
    ],
    "Other Systems": [
        "12 Notes per Octave",
        "24 Notes per Octave",
        "48 Notes per Octave",
        "72 Notes per Octave",
        "1/4 Comma Meantone Temperament",
        "Approximated Equal Tunings",
        "Just Intonation",
        "Distorted Harmonic Series",
    ],
}

