

export type MusicType = string

export type InstrumentationCategory = "Instrumentation" | "Instruments" | "Electronic Resources"

export type InstrumentationAndResources = {
    [key in InstrumentationCategory]: string[]
}

export type TuningSystemCategory =
    | "Equal Divisions of the Octave (EDO)"
    | "Equal Divisions of Other Intervals"
    | "Other Systems"

export type TuningSystems = {
    [key in TuningSystemCategory]: string[]
}
// Define the MusicEntry type
export type MusicEntry = {
    category: string;
    title: string;
    year: string;
    instrumentation: string;
    duration: string;
    additionalInfo?: string;
    description: string;
    videoLinks?: string[];
    scoreLink?: string;
    typeOfMusic: string;
    instrumentationResources: string;
    tuningSystems: string;
};

export const allEntries: MusicEntry[] =
    [
        {
            category: "Compositions",
            title: "... spiraling.",
            year: "2024/2025",
            instrumentation: "for the Lumatone",
            duration: "1'30''",
            description: "Written in commemoration of Alexandra Mouroutsou's 10th birthday.",
            typeOfMusic: "Concert Music, Instrumental, Microtonal",
            instrumentationResources: "Lumatone, Pianoteq, Solo",
            tuningSystems: "19EDO"
        },
        {
            category: "Compositions",
            title: "Contigo",
            year: "2023",
            instrumentation: "for Soprano and Piano",
            duration: "3'",
            additionalInfo: "Poem by Eugénio de Andrade.",
            description: 'Written for duo interdito (Sofia Marafona and Duarte Pereira Martins) for their project "O Caderno de Eugénio".',
            videoLinks: ["https://www.youtube.com/watch?v=sje-9JSeY4o"],
            scoreLink: "Excerpt: https://8bfb0c4a-9145-4292-aa38-862bb8c72be2.filesusr.com/ugd/644baf_4535701f090d4a388aaf5515485d59d0.pdf",
            typeOfMusic: "Concert Music, (Quasi-)Microtonal, Song, Vocal",
            instrumentationResources: "Duo, Piano, Voice (Soprano)",
            tuningSystems: "12 Notes per Octave, Just Intonation"
        },
        {
            category: "Compositions",
            title: "Convergence",
            year: "2023",
            instrumentation: "for Sinfonietta",
            duration: "20'",
            description: 'Part of the doctoral research project "(Un)Equal Tunings: Exploring multiple levels of resolution between Equal Tunings and intonational practices in composition" at Guildhall School of Music and Drama. To be published alongside the thesis.',
            typeOfMusic: "Concert Music, Instrumental, Microtonal, Orchestral, Microtonal",
            instrumentationResources: "Bassoon, Cello, Clarinet (Bb), Double Bass, Flute (C), Flute (Piccolo), Horn (F), Oboe (Soprano), Oboe (Cor Anglais), Percussion, Sinfonietta, Trombone (Tenor), Trombone (Bass), Trumpet (Bb), Tuba, Viola, Violin",
            tuningSystems: "2EDO, 3EDO, 4EDO, 5EDO, 6EDO, 7EDO, 8EDO, 9EDO, 11EDO, 13EDO, 17EDO, 19EDO, 23EDO, 2ED5\\12EDO, 2ED7\\12EDO, 12 Notes per Octave, 24 Notes per Octave, 48 Notes per Octave, Approximated Equal Tunings, Just Intonation"
        },
        {
            category: "Compositions",
            title: "Adão",
            year: "2020",
            instrumentation: "a Chamber Opera for 4 Singers and Mixed Ensemble",
            duration: "17'",
            additionalInfo: "Libretto by Nuno Cruz.",
            description: 'Second entry of the "Contos da Criação" ("Tales of Creation") cycle, based on Lilith\'s chapter on the Alphabet of Ben Sirach. Written for the "Maratona Ópera XXI - Concurso para novas óperas" and premiered during OperaFest Lisboa 2020 at Museu Nacional de Arte Antiga by Tiago Matos (Adam, baritone), Mariana Castello-Branco (Lilith, soprano), Rita Filipe (Eve, mezzo), Carlos Monteiro (Angel, tenor), Ensemble MPMP, Pedro Vieira de Almeida (electric piano), conducted by Rita Castro Blanco and directed by António Pires. Part of the doctoral research project "(Un)Equal Tunings: Exploring multiple levels of resolution between Equal Tunings and intonational practices in composition" at Guildhall School of Music and Drama. To be published alongside the thesis.',
            videoLinks: ["https://www.youtube.com/watch?v=WwP_RVeQ_8Y"],
            typeOfMusic: "Microtonal, Opera (Chamber), Vocal",
            instrumentationResources: "Accordion, bitKlavier, Cello, Clarinet (Bb), Clarinet (Bass), Keyboard (MIDI), Mixed Ensemble, Saxophone (Alto), Saxophone (Tenor), Violin, Voice (Baritone), Voice (Mezzo), Voice (Soprano), Voice (Tenor)",
            tuningSystems: "5EDO, 6EDO, 7EDO, 9EDO, 10EDO, 11EDO, 12 Notes per Octave, 48 Notes per Octave, 72 Notes per Octave, Approximated Equal Tunings, Just Intonation"
        },
        {
            category: "Compositions",
            title: "PRISM",
            year: "2020",
            instrumentation: "Acousmatic",
            duration: "40'",
            additionalInfo: "",
            description: 'Written in collaboration with Félix Xavier (choreography, performance), Vítor Hugo Afonso (performance) and Rafael Filipe (performance) for the dance performance "PRISM" (https://www.youtube.com/channel/UCkvALHCJQM3_1Tds2sEdX2g). For more information about the project click here (https://prismwuwei.wixsite.com/travellers).',
            videoLinks: ["https://www.youtube.com/watch?v=fQnDYNsEvaY"],
            typeOfMusic: "Electroacoustic (Acousmatic), Music for Dance",
            instrumentationResources: "2 Speakers",
            tuningSystems: "7EDO, 8EDO, 9EDO, 10EDO, 12EDO, 17EDO, 19EDO, 48EDO, Just Intonation, Distorted Harmonic Series"
        },
        {
            category: "Compositions",
            title: "Have you ever met a human before?",
            year: "2019",
            instrumentation: "for Soprano and MIDI Keyboard",
            duration: "3'30''",
            additionalInfo: "Lyrics by Edward Einhorn (https://www.edwardeinhorn.com/).",
            description: 'Adapted from an aria from the opera "The Boy Who Wanted to be a Robot".',
            videoLinks: [],
            typeOfMusic: "Concert Music, Microtonal, Song, Vocal",
            instrumentationResources: "bitklavier, Duo, Keyboard (MIDI), Voice (Soprano)",
            tuningSystems: "17EDO, 12 Notes per Octave, 24 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "Transeuntes",
            year: "2019",
            instrumentation: "",
            duration: "27'",
            additionalInfo: "",
            description: 'Incidental music written for the Seller Danza\'s contemporary dance performance "Transeuntes" ("Passers-by"). Choreographed by Juan Maria Seller.',
            videoLinks: [
                "https://www.youtube.com/watch?v=T66FvUUuJpg",
                "https://www.youtube.com/watch?v=zIuBLoC2NbQ",
                "https://www.youtube.com/watch?v=7g2IBdn9x7Q",
                "https://pedroffinisterra.bandcamp.com/album/transeuntes"
            ],
            typeOfMusic: "Electroacoustic (Acousmatic), Electroacoustic (Mixed), Music for Dance, VST",
            instrumentationResources: "2 Speakers",
            tuningSystems: ""
        },
        {
            category: "Compositions",
            title: "Babel",
            year: "2019",
            instrumentation: "for Mixed Choir",
            duration: "6'",
            additionalInfo: "Based on a poem by Edward Einhorn (https://www.edwardeinhorn.com/), with translations into multiple languages by friends, colleagues and former teachers of mine. Written for Choral Chameleon during the 2019 Choral Chameleon Institute.",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=t88u4xz8Lac"],
            scoreLink: "Excerpt: https://8bfb0c4a-9145-4292-aa38-862bb8c72be2.filesusr.com/ugd/644baf_68411c9e6d404100a5019e60f660e19f.pdf",
            typeOfMusic: "Choral, Concert Music, Microtonal, (Quasi-)Microtonal Music, Vocal",
            instrumentationResources: "Choir (SATB), Voice (Alto), Voice (Bass), Voice (Soprano), Voice (Tenor)",
            tuningSystems: "1ED11\\12EDO, 2ED11\\12EDO, 3ED11\\12EDO, 4ED11\\12EDO, 5ED11\\12EDO, 6ED11\\12EDO, 7ED11\\12EDO, 8ED11\\12EDO, 9ED11\\12EDO, 12 Notes per Octave, 24 Notes per Octave, Approximated Equal Tunings"
        },
        {
            category: "Compositions",
            title: "El Laberinto de Nijinsky",
            year: "2019",
            instrumentation: "",
            duration: "11'",
            additionalInfo: "",
            description: 'A Seller Danza\'s contemporary dance performance. Choreographed by Juan Maria Seller and performed by Roberto Seller. With excerpts from recordings of "MA.RIM.BA" and "Multidão: I. Primeiro".',
            videoLinks: ["https://www.youtube.com/watch?v=nZXaej6lnkA"],
            typeOfMusic: "Music for Dance",
            instrumentationResources: "",
            tuningSystems: ""
        },
        {
            category: "Compositions",
            title: "Seeking Gnosis",
            year: "2022/2023",
            instrumentation: "for Mixed Ensemble",
            duration: "13'",
            description: 'Part of the doctoral research project "(Un)Equal Tunings: Exploring multiple levels of resolution between Equal Tunings and intonational practices in composition" at Guildhall School of Music and Drama. To be published alongside the thesis.',
            typeOfMusic: "Chamber, Concert Music, Instrumental, Microtonal",
            instrumentationResources: "Bassoon, Cello, Clarinet (Bb), Clarinet (Bass), Flute (C), Flute (Alto), Flute (Piccolo), Guitar (Electric), Mixed Ensemble, Percussion, Saxophone (Alto), Viola",
            tuningSystems: "5EDO, 11EDO, 4ED11/7, 12 Notes per Octave, 24 Notes per Octave, 48 Notes per Octave, Approximated Equal Tunings, Just Intonation"
        },
        {
            category: "Compositions",
            title: "The Fable of the Pilgrim",
            year: "2022/2023",
            instrumentation: "for Guitar Quartet",
            duration: "12'",
            description: 'Part of the doctoral research project "(Un)Equal Tunings: Exploring multiple levels of resolution between Equal Tunings and intonational practices in composition" at Guildhall School of Music and Drama. To be published alongside the thesis.',
            typeOfMusic: "Chamber, Concert Music, Instrumental, Microtonal",
            instrumentationResources: "Guitar (Classical), Guitar Quartet",
            tuningSystems: "5EDO, 7EDO, 11EDO, 12 Notes per Octave, 24 Notes per Octave, 48 Notes per Octave, Approximated Equal Tunings, Just Intonation"
        },
        {
            category: "Compositions",
            title: "Odd [s]Paces",
            year: "2021/2023",
            instrumentation: "for String Quartet",
            duration: "6'",
            description: 'Part of the doctoral research project "(Un)Equal Tunings: Exploring multiple levels of resolution between Equal Tunings and intonational practices in composition" at Guildhall School of Music and Drama. To be published alongside the thesis.',
            typeOfMusic: "Chamber, Concert Music, Instrumental, Microtonal",
            instrumentationResources: "Cello, String Quartet, Viola, Violin",
            tuningSystems: "1ED3/2, 2ED3/2, 3ED3/2, 4ED3/2, 5ED3/2, 6ED3/2, 7ED3/2, 12 Notes per Octave, 24 Notes per Octave, 48 Notes per Octave, Approximated Equal Tunings, Just Intonation"
        },
        {
            category: "Compositions",
            title: "Dreams from an Old Memory",
            year: "2020",
            instrumentation: "for Electric Piano and Electronics",
            duration: "6'",
            description: 'Based on Joseph Yasser\'s writings on temperament theory and the Stasimon Chorus of Euripedes\'s "Orestes". Part of the doctoral research project "(Un)Equal Tunings: Exploring multiple levels of resolution between Equal Tunings and intonational practices in composition" at Guildhall School of Music and Drama. To be published alongside the thesis.',
            typeOfMusic: "Concert Music, Electroacoustic (Mixed), Instrumental, Microtonal",
            instrumentationResources: "2 Speakers, bitKlavier, Keyboard (MIDI), Max/MSP, Solo",
            tuningSystems: "5EDO, 7EDO, 12EDO, 19EDO, 31EDO, 50EDO"
        },
        {
            category: "Compositions",
            title: "A Escolha de Paulo",
            year: "2020",
            instrumentation: "for Violin and Piano",
            duration: "5'",
            description: 'Written for the Conservatório de Música de Santarém\'s production of Bernardo Santareno\'s play "O Bailarino", directed by José Manuel Rodrigues and choreographed by Juan Maria Seller.',
            videoLinks: ["https://www.youtube.com/watch?v=v5kzRweEB0M"],
            scoreLink: "Excerpt: https://8bfb0c4a-9145-4292-aa38-862bb8c72be2.filesusr.com/ugd/644baf_5c1406c161364b86bea3b594e0b5de9e.pdf",
            typeOfMusic: "Chamber, Concert Music, Instrumental, (Quasi-)Microtonal, Music for Dance",
            instrumentationResources: "Duo, Piano, Violin",
            tuningSystems: "12 Notes per Octave, 24 Notes per Octave, Just Intonation"
        },
        {
            category: "Compositions",
            title: "Ne Ago",
            year: "2019",
            instrumentation: "Acousmatic",
            duration: "4'30''",
            description: "Composed during the Åke Parmerud’s International Masterclass at Lisboa Incomum in April 2019, with Åke Parmerud's supervision. Later expanded to be included in the dance project, 'PRISM' by WuWei Travelers, choreographed by Félix Xavier.",
            videoLinks: ["https://www.youtube.com/watch?v=6xXhNt_vpcY"],
            scoreLink: "",
            typeOfMusic: "Electroacoustic (Acousmatic)",
            instrumentationResources: "2 Speakers",
            tuningSystems: "10EDO, 12EDO, Distorted Harmonic Series"
        },
        {
            category: "Compositions",
            title: "La vojaĝo",
            year: "2019",
            instrumentation: "for Pierrot Ensemble with Percussion",
            duration: "5'30''",
            description: "Written for the Ensemble Offspring during Noosa ISAM, with the supervisions of Ofer Ben-Amots and Jan Jirásek.",
            videoLinks: ["https://www.youtube.com/watch?v=OXOg7pixHIM"],
            scoreLink: "Excerpt: https://8bfb0c4a-9145-4292-aa38-862bb8c72be2.filesusr.com/ugd/644baf_d302725fd7fd429e90131895391d8804.pdf",
            typeOfMusic: "Chamber, Concert Music, Instrumental, Microtonal",
            instrumentationResources: "Cello, Clarinet (Bb), Flute (C), Mixed Ensemble, Percussion, Piano, Violin",
            tuningSystems: "5EDO, 7EDO, 12 Notes per Octave, 24 Notes per Octave, 48 Notes per Octave, Approximated Equal Tunings"
        },
        {
            category: "Compositions",
            title: "MA.RIM.BA",
            year: "2018",
            instrumentation: "for Marimba & Electronics",
            duration: "5'",
            description: "Written for Cristiano Rios.",
            videoLinks: ["https://oneglasseye.bandcamp.com/track/ma-rim-ba"],
            scoreLink: "Excerpt: https://8bfb0c4a-9145-4292-aa38-862bb8c72be2.filesusr.com/ugd/644baf_d5c0ae9b5607448589ee70922e57a6ff.pdf",
            typeOfMusic: "Concert Music, Electroacoustic (Mixed), Instrumental",
            instrumentationResources: "2 Speakers, Max/MSP, Percussion, Solo",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "The Boy Who Wanted to be a Robot",
            year: "2018",
            instrumentation: "a Chamber Opera for 5 Singers, Operatic Choir, and Mixed Ensemble",
            duration: "24'",
            description: "Written as the main project of my MA on Opera Making & Writing at Guildhall School of Music and Drama, during the 2017/2018 academic year. Libretto by Edward Einhorn.",
            videoLinks: ["http://youtube.com/watch?v=IDM0THAddQs"],
            scoreLink: "Excerpt: https://8bfb0c4a-9145-4292-aa38-862bb8c72be2.filesusr.com/ugd/644baf_3a857159c0944a99a50721b823221de7.pdf",
            typeOfMusic: "Microtonal, (Quasi-)Microtonal, Opera (Chamber), Vocal",
            instrumentationResources: "bitklavier, Cello, Choir (Operatic), Clarinet (Bb), Clarinet (Bass), Double Bass, Flute (C), Flute (Piccolo), Harp, Keyboard (MIDI), Max/MSP, Mixed Ensemble, Percussion, Piano, Viola, Violin, Voice (Baritone), Voice (Mezzo), Voice (Soprano), Voice (Tenor)",
            tuningSystems: "17EDO, 12 Notes per Octave, 24 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "Nymphus: Mithraic Initiation Rite Number Two",
            year: "2017",
            instrumentation: "a Short Opera Scene for 3 Singers and Piano",
            duration: "7'30''",
            description: "Written in the context of my MA on Opera Making & Writing at Guildhall School of Music and Drama, during the 2017/2018 academic year. Libretto by Edward Einhorn.",
            videoLinks: ["https://www.youtube.com/watch?v=-A3b3joAFPA"],
            scoreLink: "Excerpt: https://8bfb0c4a-9145-4292-aa38-862bb8c72be2.filesusr.com/ugd/644baf_5fd76c3f541340a7a8b7738d21d6110b.pdf",
            typeOfMusic: "Opera (Chamber), Vocal",
            instrumentationResources: "Piano, Voice (Baritone), Voice (Mezzo), Voice (Tenor)",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "Multidão - I. Primeiro",
            year: "2017",
            instrumentation: "the first act of a Monodrama for Countertenor and Mixed Ensemble",
            duration: "14'",
            additionalInfo: "Libretto by Nuno Cruz.",
            description: "Written for Rui Vieira.",
            videoLinks: ["https://www.youtube.com/watch?v=fl5wrPwH8ns"],
            scoreLink: "Full score preview: https://portfolios.esml.ipl.pt/oprojecto/90-criacao-circulacao-registo-audio-e-edicao-de-obras-de-musica-portuguesa-contemporanea-numa-perspetiva-reflexiva/133-multidao-i-primeiro",
            typeOfMusic: "(Quasi-)Microtonal, Opera (Chamber), Opera (Monodrama), Vocal",
            instrumentationResources: "Cello, Clarinet (Bb), Clarinet (Bass), Double Bass, Flute (C), Flute (Alto), Harp, Horn (F), Mixed Ensemble, Percussion, Violin, Voice (Countertenor)",
            tuningSystems: "12 Notes per Octave, 24 Notes per Octave, 48 Notes per Octave, Distorted Harmonic Series"
        },
        {
            category: "Compositions",
            title: "@ctb.exp#1",
            year: "2017",
            instrumentation: "for Solo Double Bass",
            duration: "3'30''",
            description: "Commissioned by RTP/Antena 2 for the 31st Edition of the 'Prémio Jovens Músicos' Festival.",
            videoLinks: ["https://www.youtube.com/watch?v=trajxDl1b9c"],
            scoreLink: "For purchase: https://www.scherzoeditions.com/webshop/shop/ctb-exp1-para-contrabaixo-pedro-f-finisterra/",
            typeOfMusic: "Concert Music, Instrumental",
            instrumentationResources: "Double Bass, Solo",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "Flor",
            year: "2016",
            instrumentation: "a chamber music piece for Mixed Ensemble with Electronics, written for a Music/Dance performance",
            duration: "4'",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=H9vDP-Ml4cM"],
            scoreLink: "Full score preview: https://portfolios.esml.ipl.pt/oprojecto/89-performance-colaborativa-fmh-esml/116-flor",
            typeOfMusic: "Chamber, Concert Music, Electroacoustic (Mixed), Instrumental, Music for Dance, (Quasi-)Microtonal",
            instrumentationResources: "1 or 2 Speakers, Cello, Double Bass, Flute (C), Max/MSP, Mixed Ensemble, Piano, Violin",
            tuningSystems: "12 Notes per Octave, 24 Notes per Octave, Distorted Harmonic Series"
        },
        {
            category: "Compositions",
            title: "Lilith",
            year: "2016",
            instrumentation: "a Narrated Tale for Narrator, 2 Singers and Small Wind Orchestra",
            duration: "25'",
            additionalInfo: "Libretto by Nuno Cruz.",
            description: "First entry of the 'Contos da Criação' ('Tales of Creation') cycle, based on Lilith's chapter on the Alphabet of Ben Sirach.",
            videoLinks: ["https://www.youtube.com/watch?v=R0ZDQ-6TrhQ"],
            scoreLink: "",
            typeOfMusic: "Opera (Narrated Tale), Vocal",
            instrumentationResources: "Bassoon, Clarinet (Bb), Flute (C), Guitar (Classical), Harp, Horn (F), Oboe (Soprano), Percussion, Piano, Trombone (Tenor), Trumpet (Bb), Tuba, Voice (Baritone), Voice (Narrator), Voice (Soprano), Wind Orchestra (Small)",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "¡¿Lamento?!",
            year: "2016",
            instrumentation: "for Mixed Ensemble",
            duration: "7'",
            description: "Based on Henry Purcell’s 'Dido & Eneas' and written for ClusterLAB.",
            videoLinks: ["https://www.youtube.com/watch?v=pWzALCt9cws"],
            scoreLink: "Full score preview: https://portfolios.esml.ipl.pt/oprojecto/98-old-is-new-concerto-1/84-lamento",
            typeOfMusic: "Chamber, Concert Music, Instrumental, (Quasi-)Microtonal",
            instrumentationResources: "Cello, Double Bass, Flute (C), Mixed Ensemble, Oboe (Soprano), Viola, Violin",
            tuningSystems: "12 Notes per Octave, 24 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "Expressões",
            year: "2015",
            instrumentation: "a chamber music piece for Mixed Ensemble written for a Music/Dance performance",
            duration: "4'",
            additionalInfo: "Choreography and performance by: Jessica Silva & Mara Morais.",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=i-wkHVZy-7g"],
            scoreLink: "Excerpt: https://8bfb0c4a-9145-4292-aa38-862bb8c72be2.filesusr.com/ugd/644baf_ed62ca3a0a6e4d06995ebf07a93cb1aa.pdf",
            typeOfMusic: "Chamber, Concert Music, Instrumental, (Quasi-)Microtonal, Music for Dance",
            instrumentationResources: "Cello, Clarinet (Bb), Double Bass, Flute (C), Mixed Ensemble, Violin",
            tuningSystems: "12 Notes per Octave, 24 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "Introspecções",
            year: "2014/2015",
            instrumentation: "for Wind Trio",
            duration: "8'",
            additionalInfo: "Written originally for the second edition of the festival Peças Frescas - Edição Açores S. Miguel (https://www.youtube.com/channel/UCNYOm6I2-P72-qP6Mh8q8dQ), Azores, Portugal in 2015.",
            description: "",
            videoLinks: ["http://youtube.com/watch?v=pPvtiPMlaw4"],
            scoreLink: "Excerpt: https://8bfb0c4a-9145-4292-aa38-862bb8c72be2.filesusr.com/ugd/644baf_0d2194cf6b614166bcbc3d5536a8ba36.pdf",
            typeOfMusic: "Chamber, Concert Music, Instrumental",
            instrumentationResources: "Bassoon, Clarinet (Bb), Flute (C), Trio",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "Prjkt.Hrp",
            year: "2015",
            instrumentation: "for Harp and Electronics",
            duration: "8'30''",
            additionalInfo: "Written for Inês Cavalheiro.",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=6J6KFcayW74"],
            scoreLink: "Score preview: https://portfolios.esml.ipl.pt/oprojecto/95-semana-da-composicao-2015/156-prjkt-hrp",
            typeOfMusic: "Concert Music, Electroacoustic (Mixed), Instrumental",
            instrumentationResources: "2 Speakers, Harp, Max/MSP, Solo",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "Eu não sei…",
            year: "2015",
            instrumentation: "for Baritone and Pipe Organ",
            duration: "4'30''",
            additionalInfo: "Poem by Duarte Cruz.",
            description: "Written for João Fonseca e Costa and Pedro Pombo.",
            videoLinks: ["https://www.youtube.com/watch?v=N-Yz9AJJlmc"],
            scoreLink: "",
            typeOfMusic: "Concert Music, Song, Vocal",
            instrumentationResources: "Duo, Organ (Pipe), Voice (Baritone)",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "Plácidos Domingos",
            year: "2014/2015",
            instrumentation: "for Baritone and Piano",
            duration: "2'",
            additionalInfo: "Poem by Nuno Cruz.",
            description: "Written for João Fonseca e Costa (adapted from an earlier version for Tenor and Piano).",
            videoLinks: [],
            scoreLink: "",
            typeOfMusic: "Concert Music, Song, Vocal",
            instrumentationResources: "Duo, Piano, Voice (Baritone)",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "8-bits of Music",
            year: "2014",
            instrumentation: "for Solo Harpsichord",
            duration: "14'",
            additionalInfo: "Written for Leonora Silva and Catarina Amante Trigo (https://www.catarinatrigo.com/).",
            description: "",
            videoLinks: ["https://www.youtube.com/playlist?list=PL6VcdiGfTfX6k8hNDNVxpS0hOIy3kLXpY"],
            scoreLink: "",
            typeOfMusic: "Concert Music, Instrumental",
            instrumentationResources: "Harpsichord, Solo",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "7",
            year: "2014",
            instrumentation: "for Amplified Soprano and Mixed Ensemble",
            duration: "4'",
            additionalInfo: "",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=-_lkcsjPGds"],
            scoreLink: "Excerpt: https://8bfb0c4a-9145-4292-aa38-862bb8c72be2.filesusr.com/ugd/644baf_0757df4751e74c8a8ba01b179fc951aa.pdf",
            typeOfMusic: "Chamber, Concert Music, Instrumental, Vocal",
            instrumentationResources: "1 or 2 Speakers, Cello, Clarinet (Bb), Flute (C), Mixed Ensemble, Percussion, Piano, Violin, Voice (Soprano)",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "Flip Point & Obsession",
            year: "2014",
            instrumentation: "for Solo Piano",
            duration: "5'30''",
            additionalInfo: "",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=_8ObX6182o0"],
            scoreLink: "Score preview: https://portfolios.esml.ipl.pt/oprojecto/96-semana-da-composicao-2016/115-flip-point-obsession",
            typeOfMusic: "Concert Music, Instrumental",
            instrumentationResources: "Piano, Solo",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "Óvaadasac",
            year: "2014",
            instrumentation: "Acousmatic",
            duration: "3'",
            additionalInfo: "",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=jCNf8mFrmWY"],
            scoreLink: "",
            typeOfMusic: "Electroacoustic (Acousmatic)",
            instrumentationResources: "2 Speakers",
            tuningSystems: ""
        },
        {
            category: "Compositions",
            title: "Harp' N Roll",
            year: "2014",
            instrumentation: "for Solo Harp",
            duration: "3'",
            additionalInfo: "",
            description: "",
            videoLinks: [],
            scoreLink: "",
            typeOfMusic: "Concert Music, Instrumental",
            instrumentationResources: "Harp, Solo",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "Estudo para Guitarra nº2",
            year: "2014",
            instrumentation: "for Solo Guitar",
            duration: "1'",
            additionalInfo: "",
            description: "",
            videoLinks: [],
            scoreLink: "",
            typeOfMusic: "Concert Music, Instrumental",
            instrumentationResources: "Guitar (Classical), Solo",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "Dryhg oui - II",
            year: "2014",
            instrumentation: "for Clarinet, Cello and Piano",
            duration: "3'",
            additionalInfo: "Part of the \"Dryhg oui\" cycle, dedicated to my first composition teacher, Jorge Pereira.",
            description: "",
            videoLinks: [],
            scoreLink: "",
            typeOfMusic: "Chamber, Concert Music, Instrumental",
            instrumentationResources: "Cello, Clarinet (Bb), Piano, Trio",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "4 Pequenas Peças para Piano",
            year: "2013/2014",
            instrumentation: "for Solo Piano",
            duration: "3'30''",
            additionalInfo: "",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=OO84Wd7tfuo"],
            scoreLink: "",
            typeOfMusic: "Concert Music, Instrumental",
            instrumentationResources: "Piano, Solo",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "Dryhg oui - I",
            year: "2013",
            instrumentation: "for Cello and Piano",
            duration: "1'30''",
            additionalInfo: "Part of the \"Dryhg oui\" cycle, dedicated to my first composition teacher, Jorge Pereira.",
            description: "",
            videoLinks: [],
            scoreLink: "",
            typeOfMusic: "Chamber, Concert Music, Instrumental",
            instrumentationResources: "Cello, Duo, Piano",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "Tributo a Masashi Hamauzu",
            year: "2012",
            instrumentation: "for Solo Piano",
            duration: "5'",
            additionalInfo: "Written in tribute to the German/Japanese composer Masashi Hamauzu.",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=15OFS9mvX6Y"],
            scoreLink: "",
            typeOfMusic: "Concert Music, Instrumental",
            instrumentationResources: "Piano, Solo",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "Aurora",
            year: "2012",
            instrumentation: "for Mixed Choir (SATBB)",
            duration: "3'30''",
            additionalInfo: "",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=_E6kXfSjeM4"],
            scoreLink: "",
            typeOfMusic: "Choral, Concert Music, Vocal",
            instrumentationResources: "Choir (SATBB), Voice (Alto), Voice (Baritone), Voice (Bass), Voice (Soprano), Voice (Tenor)",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "2 Prelúdios para Guitarra",
            year: "2008/2010",
            instrumentation: "for Solo Guitar",
            duration: "13'",
            additionalInfo: "\"I. Prelúdio nº1: Homenagem a Iserlohn (2008)\nII. Prelúdio nº2 (2010)\"",
            description: "",
            videoLinks: ["https://www.youtube.com/playlist?list=PL6VcdiGfTfX7tCZ1FNuZNaoLfL7rTp1nx"],
            scoreLink: "",
            typeOfMusic: "Concert Music, Instrumental",
            instrumentationResources: "Guitar (Classical), Solo",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "1521 Gotas de Chuva",
            year: "2008",
            instrumentation: "for Solo Piano",
            duration: "4'",
            additionalInfo: "",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=RlvYXs4mpNI"],
            scoreLink: "",
            typeOfMusic: "Concert Music, Instrumental",
            instrumentationResources: "Piano, Solo",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "Estudo para Guitarra nº1",
            year: "2008",
            instrumentation: "for Solo Guitar",
            duration: "1'",
            additionalInfo: "Dedicated to my guitar teacher Acácio Resende.",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=viGqiocGRsg"],
            scoreLink: "",
            typeOfMusic: "Concert Music, Instrumental",
            instrumentationResources: "Guitar (Classical), Solo",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Compositions",
            title: "Paz de Espírito",
            year: "2007",
            instrumentation: "for Solo Guitar",
            duration: "3'",
            additionalInfo: "",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=X4mExOf3YxQ"],
            scoreLink: "",
            typeOfMusic: "Concert Music, Instrumental",
            instrumentationResources: "Guitar (Classical), Solo",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Improvisations",
            title: "Submerged",
            year: "2024",
            instrumentation: "",
            duration: "5'",
            additionalInfo: "",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=p0cUcI140HE"],
            scoreLink: "",
            typeOfMusic: "Instrumental, Microtonal",
            instrumentationResources: "Lumatone, Pianoteq, Solo",
            tuningSystems: "29EDO"
        },
        {
            category: "Improvisations",
            title: "... for Glenn",
            year: "2023",
            instrumentation: "",
            duration: "3'",
            additionalInfo: "",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=vZbrgxQVM_k"],
            scoreLink: "",
            typeOfMusic: "Instrumental, Microtonal",
            instrumentationResources: "Lumatone, Pianoteq, Solo",
            tuningSystems: "19EDO"
        },
        {
            category: "Improvisations",
            title: "... in the name of peace #2",
            year: "2023",
            instrumentation: "",
            duration: "11'",
            additionalInfo: "",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=Wf0WqkhvEck"],
            scoreLink: "",
            typeOfMusic: "Instrumental, Microtonal",
            instrumentationResources: "Lumatone, Pianoteq, Solo",
            tuningSystems: "26EDO"
        },
        {
            category: "Improvisations",
            title: "... in the name of peace #1",
            year: "2023",
            instrumentation: "",
            duration: "7'30''",
            additionalInfo: "",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=wMMFFtJ25ww"],
            scoreLink: "",
            typeOfMusic: "Instrumental, Microtonal",
            instrumentationResources: "Lumatone, Pianoteq, Solo",
            tuningSystems: "26EDO"
        },
        {
            category: "Improvisations",
            title: "Chiptune Improvisation in 6ED7:5",
            year: "2019",
            instrumentation: "",
            duration: "2’",
            additionalInfo: "Improvised on ET Remapper (built by myself on Max/MSP, now incorporated in Equal Tuning Lab) and bitKlavier.",
            description: "",
            videoLinks: ["https://pedroffinisterra.bandcamp.com/track/chiptune-improvisation-in-6ed7-5"],
            scoreLink: "",
            typeOfMusic: "Instrumental, Microtonal",
            instrumentationResources: "bitKlavier, Keyboard (MIDI), Solo",
            tuningSystems: "6ED7/5"
        },
        {
            category: "Improvisations",
            title: "Laptop Improvisation in 7EDO",
            year: "2019",
            instrumentation: "",
            duration: "3’",
            additionalInfo: "Improvised on n-ET Microtonal Keyboard (built by myself on Max/MSP, now incorporated in Equal Tuning Lab).",
            description: "",
            videoLinks: ["https://pedroffinisterra.bandcamp.com/track/laptop-improvisation-in-7ed2-1"],
            scoreLink: "",
            typeOfMusic: "Instrumental, Microtonal",
            instrumentationResources: "Laptop, Max/MSP, Solo",
            tuningSystems: "7EDO"
        },
        {
            category: "Improvisations",
            title: "Tri Improvizajoj por MIDI​-​Klavaro",
            year: "2018",
            instrumentation: "",
            duration: "14’",
            additionalInfo: "Improvised on 12-NET Microtonal Keyboard (built by myself on Max/MSP).",
            description: "",
            videoLinks: ["https://pedroffinisterra.bandcamp.com/album/tri-improvizajoj-por-midi-klavaro"],
            scoreLink: "",
            typeOfMusic: "Instrumental, Microtonal",
            instrumentationResources: "Keyboard (MIDI), Max/MSP, Solo",
            tuningSystems: "1/4 Comma Meantone Temperament, Just Intonation, Distorted Harmonic Series"
        },
        {
            category: "Improvisations",
            title: "Improvisation in 17EDO",
            year: "2018",
            instrumentation: "",
            duration: "2’30''",
            additionalInfo: "Improvised on n-ET Microtonal Keyboard (built by myself on Max/MSP, now incorporated in Equal Tuning Lab).",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=6bvusHly1fI"],
            scoreLink: "",
            typeOfMusic: "Instrumental, Microtonal",
            instrumentationResources: "Keyboard (MIDI), Max/MSP, Solo",
            tuningSystems: "17EDO"
        },
        {
            category: "Jazz",
            title: "We are our dreams of ourselves",
            year: "2018",
            instrumentation: "",
            duration: "1'30''",
            additionalInfo: "Based on the first poem from Fernando Pessoa's '35 Sonets'.",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=mgzxm5BHWHs"],
            scoreLink: "",
            typeOfMusic: "Jazz, Vocal",
            instrumentationResources: "Drums, Guitar (Bass, Electric), Keyboard (Electric), Voice (Narrator)",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Jazz",
            title: "Epidemia do Funk",
            year: "2013/2016",
            instrumentation: "",
            duration: "9'",
            additionalInfo: "Part of Tomé Ferreira's school project EP 'Um Homem na Cidade'.",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=9m7Ot5SSGzI"],
            scoreLink: "",
            typeOfMusic: "Instrumental, Jazz",
            instrumentationResources: "Drums, Guitar (Electric), Guitar (Bass, Electric), Jazz Ensemble, Piano, Saxophone (Alto), Saxophone (Tenor), Trombone (Tenor), Trumpet (Bb)",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Jazz",
            title: "Tributo a Masashi Hamauzu '16",
            year: "2016",
            instrumentation: "",
            duration: "8'",
            additionalInfo: "Part of Tomé Ferreira's school project EP 'Um Homem na Cidade'.",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=93llCd-SxkA"],
            scoreLink: "",
            typeOfMusic: "Instrumental, Jazz",
            instrumentationResources: "Drums, Guitar (Electric), Guitar (Bass, Electric), Jazz Ensemble, Piano, Saxophone (Alto), Trombone (Tenor), Trumpet (Bb)",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Jazz",
            title: "Pré-primária",
            year: "2014",
            instrumentation: "",
            duration: "2'",
            additionalInfo: "Lyrics written by Mário Espada. Bossa Nova. Part of the soundtrack of Mário Espada's short movie 'Jingã Íncone'.",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=DwblSFpC1dw"],
            scoreLink: "",
            typeOfMusic: "Bossa Nova, Song, Vocal",
            instrumentationResources: "Bossa Nova Ensemble, Double Bass, Drums, Flute (C), Guitar (Classical), Voice (Mezzo)",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Jazz",
            title: "Hora de Ponta",
            year: "2012",
            instrumentation: "",
            duration: "4'",
            additionalInfo: "Written for Big Band Júnior's and featured on their album 'Pegadas Azuis'.",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=d716YnF-S9I", "https://open.spotify.com/track/5ozh6QZn2pHi0moMAEgHw8?si=6a8571a6c6994df9"],
            scoreLink: "",
            typeOfMusic: "Instrumental, Jazz",
            instrumentationResources: "Big Band, Clarinet (Bb), Double Bass, Drums, Flute (C), Guitar (Bass, Electric), Piano, Saxophone (Alto), Saxophone (Tenor), Trombone (Tenor), Trumpet (Bb), Violin, Voice (Tenor)",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Jazz",
            title: "Drowning",
            year: "2011",
            instrumentation: "",
            duration: "5'30''",
            additionalInfo: "Written for Big Band Júnior. The Portuguese jazz guitar player Mário Delgado featured in this performance.",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=Puj4ISWTrNI"],
            scoreLink: "",
            typeOfMusic: "Instrumental, Jazz",
            instrumentationResources: "Accordeon, Big Band, Drums, Flute (C), Guitar (Bass, Electric), Guitar (Electric), Piano, Saxophone (Alto), Trumpet (Bb), Voice (Tenor)",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Arrangements",
            title: "thank u, next - Ariana Grande",
            year: "2018/2019",
            instrumentation: "",
            duration: "3'",
            additionalInfo: "Arrangement commissioned by 'The Spell'.",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=JzA_bvDTcD4", "https://www.youtube.com/live/8l9VrKSpVZE?si=lv3sfKaQ3DtE7xF4&t=837"],
            scoreLink: "",
            typeOfMusic: "A Capella, Vocal",
            instrumentationResources: "Vocal Quartet (with Beatbox), Voice (Alto), Voice (Bass), Voice (Beatbox), Voice (Mezzo), Voice (Tenor)",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Arrangements",
            title: "Juntos Somos Mais Fortes - Amor Electro",
            year: "2017/2019",
            instrumentation: "",
            duration: "3'",
            additionalInfo: "Arrangement commissioned by 'The Spell'.",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=yG_8opUUYaI", "https://www.youtube.com/live/8l9VrKSpVZE?si=jNXqVWQBc_FgKkrI&t=1037"],
            scoreLink: "",
            typeOfMusic: "A Capella, Vocal",
            instrumentationResources: "Vocal Quartet (with Beatbox), Voice (Alto), Voice (Bass), Voice (Beatbox), Voice (Mezzo), Voice (Tenor)",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Arrangements",
            title: "Lusitana Paixão - Dulce Pontes",
            year: "2018",
            instrumentation: "",
            duration: "2'",
            additionalInfo: "Arrangement commissioned by 'The Spell'.",
            description: "",
            videoLinks: [],
            scoreLink: "",
            typeOfMusic: "A Capella, Vocal",
            instrumentationResources: "Vocal Sextet (with Beatbox), Voice (Alto), Voice (Baritone), Voice (Bass), Voice (Beatbox), Voice (Mezzo), Voice (Tenor), Voice (Soprano)",
            tuningSystems: "12 Notes per Octave"
        },
        {
            category: "Arrangements",
            title: "Desfolhada de Inverno - Simone de Oliveira",
            year: "2018",
            instrumentation: "",
            duration: "3'",
            additionalInfo: "A mashup based on 'Desfolhada Portuguesa' and 'Sol de Inverno', both originally performed by Simone de Oliveira. Arrangement commissioned by 'The Spell'.",
            description: "",
            videoLinks: ["https://www.youtube.com/watch?v=95ihtSyw4hU"],
            scoreLink: "",
            typeOfMusic: "A Capella, Vocal",
            instrumentationResources: "Vocal Octet (with Beatbox), Voice (Alto), Voice (Baritone), Voice (Bass), Voice (Beatbox), Voice (Tenor), Voice (Soprano)",
            tuningSystems: "12 Notes per Octave"
        }
    ]


export const musicTypes: MusicType[] = [
    "A Capella",
    "Bossa Nova",
    "Chamber",
    "Choral",
    "Concert Music",
    "Electroacoustic (Acousmatic)",
    "Electroacoustic (Mixed)",
    "Instrumental",
    "Jazz",
    "Microtonal",
    "(Quasi-)Microtonal",
    "Music for Dance",
    "Opera (Narrated Tale)",
    "Opera (Chamber)",
    "Opera (Monodrama)",
    "Orchestral",
    "Song",
    "VST",
    "Vocal",
]

export const instrumentationAndResources: InstrumentationAndResources = {
    Instrumentation: [
        "Big Band",
        "Bossa Nova Ensemble",
        "Choir (Operatic)",
        "Choir (SATB)",
        "Choir (SATBB)",
        "Duo",
        "Guitar Quartet",
        "Jazz Ensemble",
        "Mixed Ensemble",
        "Solo",
        "String Quartet",
        "Trio",
        "Vocal Octet (with Beatbox)",
        "Vocal Quartet (with Beatbox)",
        "Vocal Sextet (with Beatbox)",
        "Wind Orchestra (Small)",
    ],
    Instruments: [
        "Accordion",
        "Bassoon",
        "Cello",
        "Clarinet (Bb)",
        "Clarinet (Bass)",
        "Double Bass",
        "Drums",
        "Guitar (Bass, Electric)",
        "Guitar (Classical)",
        "Guitar (Electric)",
        "Flute (C)",
        "Flute (Alto)",
        "Flute (Piccolo)",
        "Harp",
        "Horn (F)",
        "Keyboard (Electric)",
        "Keyboard (MIDI)",
        "Laptop",
        "Lumatone",
        "Oboe (Soprano)",
        "Oboe (Cor Anglais)",
        "Organ (Pipe)",
        "Piano",
        "Percussion",
        "Saxophone (Alto)",
        "Saxophone (Tenor)",
        "Trombone (Tenor)",
        "Trombone (Bass)",
        "Trumpet (Bb)",
        "Tuba",
        "Violin",
        "Viola",
        "Voice (Alto)",
        "Voice (Baritone)",
        "Voice (Bass)",
        "Voice (Beatbox)",
        "Voice (Countertenor)",
        "Voice (Mezzo)",
        "Voice (Narrator)",
        "Voice (Soprano)",
        "Voice (Tenor)",
    ],
    "Electronic Resources": ["1 or 2 Speakers", "2 Speakers", "bitKlavier", "Max/MSP", "Pianoteq"],
}

export const tuningSystems: TuningSystems = {
    "Equal Divisions of the Octave (EDO)": [
        "2EDO",
        "3EDO",
        "4EDO",
        "5EDO",
        "6EDO",
        "7EDO",
        "8EDO",
        "9EDO",
        "10EDO",
        "11EDO",
        "12EDO",
        "13EDO",
        "17EDO",
        "19EDO",
        "23EDO",
        "26EDO",
        "29EDO",
        "31EDO",
        "48EDO",
        "50EDO",
    ],
    "Equal Divisions of Other Intervals": [
        "1ED3/2",
        "2ED3/2",
        "3ED3/2",
        "4ED3/2",
        "5ED3/2",
        "6ED3/2",
        "7ED3/2",
        "6ED7/5",
        "4ED11/7",
        "2ED5\\12EDO",
        "2ED7\\12EDO",
        "1ED11\\12EDO",
        "2ED11\\12EDO",
        "3ED11\\12EDO",
        "4ED11\\12EDO",
        "5ED11\\12EDO",
        "6ED11\\12EDO",
        "7ED11\\12EDO",
        "8ED11\\12EDO",
        "9ED11\\12EDO",
    ],
    "Other Systems": [
        "12 Notes per Octave",
        "24 Notes per Octave",
        "48 Notes per Octave",
        "72 Notes per Octave",
        "1/4 Comma Meantone Temperament",
        "Approximated Equal Tunings",
        "Just Intonation",
        "Distorted Harmonic Series",
    ],
}

